# Generated by Django 4.1.7 on 2023-06-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date',
            new_name='pub_date',
        ),
    ]
